batch_size:  16
dataset_name: FlyingChairs2
epochs: 100000
find_best_lr: false
flow_root: null
image_size: !!python/tuple
- 96
- 128
inpainting_root: /home/tnguyen/OCFlow/tensorboard_inpainting_logs/gated, vgg/checkpoints/epoch=301-step=167356.ckpt
using_pretrained_inpainting: true
learning_rate: 0.00001
log_every_n_steps: 15
check_val_every_n_epoch: 1
model: with_gt_flow
network_type: twostage
org: false
overfit: false 
reconst_weight: 1.0
pixelwise_weight: 2.0
root: /home/tnguyen/dataset/FlyingChairs2/train
n_display_images: 3
log_image_every_epoch: 1
photo_weight: 4.0
smooth1_weight: 0.5
smooth2_weight: 0.0
displacement: 4
supervised_flow: true
inpainting_stage: gated
with_occ: false
static_occ: false
occ_aware: true
occlusion_ratio: 0.3
result_dir: occlusion_mask_logs
loss_type: pixel-wise
adversarial_loss: false