batch_size: 32
dataset_name: FlyingChairsInpainting
epochs: 5000
find_best_lr: false
flow_root: null
image_size: !!python/tuple
- 96
- 128
inpainting_root: /home/tnguyen/OCFlow/tensorboard_logs/default/gated, random , 0.001/checkpoints/epoch=565.ckpt
learning_rate: 0.001
log_every_n_steps: 15
model: gated
network_type: inpainting
org: false
overfit: false
reconst_weight: 0.0
root: /home/tnguyen/dataset/FlyingChairs2/train
n_display_images: 3
log_image_every_epoch: 1
photo_weight: 1.0
smooth1_weight: 0.0
smooth2_weight: 1.0
displacement: 4
supervised_flow: true
inpainting_stage: gated
with_occ: false
static_occ: false
occ_aware: true
occlusion_ratio: 0.3
result_dir: gan_img_logs
loss_type: vgg
adversarial_loss: true