batch_size: 16
dataset_name: MpiSintelCleanInpainting
epochs: 1000
find_best_lr: false
flow_root: null
image_size: !!python/tuple
- 64
- 128
inpainting_root: null
learning_rate: 0.001
log_every_n_steps: 20
model: gated
network_type: inpainting
org: false
overfit_batches: 0
reconst_weight: 1.0
root: D:\MPI-Sintel-complete\data
second_order_weight: 0.0
smoothness_penalty: 0.05
supervised_flow: true
with_occ: false
static_occ: false