batch_size: 64
dataset_name: FlyingChairsInpainting
epochs: 5000
find_best_lr: false
flow_root: null
image_size: !!python/tuple
- 64
- 128
inpainting_root: null
learning_rate: 0.002
log_every_n_steps: 15
model: gated
network_type: inpainting
org: true
overfit: false
reconst_weight: 1.0
root: /home/tnguyen/dataset/FlyingChairs_release/data
n_display_images: 3
log_image_every_epoch: 1
second_order_weight: 0.0
smoothness_penalty: 0.05
supervised_flow: true
with_occ: false
static_occ: false
occlusion_ratio: 0.5
result_dir: gan_img_logs