batch_size: 64
dataset_name: FlyingChairs2
epochs: 5000
find_best_lr: true
flow_root: null
image_size: !!python/tuple
- 64
- 128
inpainting_root: /home/tnguyen/OCFlow/tensorboard_logs/default/version_1/checkpoints/epoch=565.ckpt
learning_rate: 0.004
log_every_n_steps: 15
model: with_gt_flow
network_type: twostage
org: true
overfit: false
reconst_weight: 0.5
root: /home/tnguyen/dataset/FlyingChairs2/train
n_display_images: 3
log_image_every_epoch: 1
second_order_weight: 0.0
smoothness_penalty: 0.05
supervised_flow: true
inpainting_stage: gated
with_occ: false
static_occ: false
occ_aware: true
occlusion_ratio: 0.5
result_dir: gan_img_logs